/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testscaler;

import java.io.FileNotFoundException;
import testscaler.TSAddClass;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import testscaler.Class;

/**
 *
 * @author derri
 */
public class TSMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form TSMainWindow
     */
    public TSMainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddClassButton = new javax.swing.JButton();
        NewTestButton = new javax.swing.JButton();
        EditClassButton = new javax.swing.JButton();
        EditTestButton = new javax.swing.JButton();
        RemoveClassButton = new javax.swing.JButton();
        RemoveTestButton = new javax.swing.JButton();
        ViewClassesButton = new javax.swing.JButton();
        ViewTestsButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Scaler");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        AddClassButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AddClassButton.setText("Add Class");
        AddClassButton.setPreferredSize(new java.awt.Dimension(50, 50));
        AddClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClassButtonActionPerformed(evt);
            }
        });

        NewTestButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NewTestButton.setText("New Test");
        NewTestButton.setActionCommand("NewTestBUtton");
        NewTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewTestButtonActionPerformed(evt);
            }
        });

        EditClassButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EditClassButton.setText("Edit Class");
        EditClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClassButtonActionPerformed(evt);
            }
        });

        EditTestButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EditTestButton.setText("Edit Test");
        EditTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTestButtonActionPerformed(evt);
            }
        });

        RemoveClassButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RemoveClassButton.setText("Remove Class");
        RemoveClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveClassButtonActionPerformed(evt);
            }
        });

        RemoveTestButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RemoveTestButton.setText("Remove Test");
        RemoveTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTestButtonActionPerformed(evt);
            }
        });

        ViewClassesButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ViewClassesButton.setText("View Classes");
        ViewClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewClassesButtonActionPerformed(evt);
            }
        });

        ViewTestsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ViewTestsButton.setText("View Tests");
        ViewTestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTestsButtonActionPerformed(evt);
            }
        });

        DoneButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewClassesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ViewTestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RemoveClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(RemoveTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(NewTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddClassButton, DoneButton, EditClassButton, EditTestButton, NewTestButton, RemoveClassButton, RemoveTestButton, ViewClassesButton, ViewTestsButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ViewClassesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewTestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddClassButton, DoneButton, EditClassButton, EditTestButton, NewTestButton, RemoveClassButton, RemoveTestButton, ViewClassesButton, ViewTestsButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClassButtonActionPerformed
        // TODO add your handling code here:
        TSAddClass window = new TSAddClass();
        window.setVisible(true);
    }//GEN-LAST:event_AddClassButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        Class classinfo = new Class();
        Test testinfo = new Test();
        try {
            classinfo.Shutdown();
        } catch (IOException ex) {
            Logger.getLogger(TSMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            testinfo.Shutdown();
        } catch (IOException ex) {
            Logger.getLogger(TSMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void ViewClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewClassesButtonActionPerformed
        // TODO add your handling code here:
        TSViewClass window = new TSViewClass();
        window.setVisible(true);
    }//GEN-LAST:event_ViewClassesButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Class classstartup = new Class();
        Test teststartup = new Test();
        try {
            classstartup.Startup();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TSMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            teststartup.Startup();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TSMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void EditClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClassButtonActionPerformed
        // TODO add your handling code here:
        TSEditClass window = new TSEditClass();
        window.setVisible(true);
    }//GEN-LAST:event_EditClassButtonActionPerformed

    private void RemoveClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveClassButtonActionPerformed
        // TODO add your handling code here:
        TSRemoveClass window = new TSRemoveClass();
        window.setVisible(true);
    }//GEN-LAST:event_RemoveClassButtonActionPerformed

    private void NewTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTestButtonActionPerformed
        // TODO add your handling code here:
        TSNewTest window = new TSNewTest();
        window.setVisible(true);
    }//GEN-LAST:event_NewTestButtonActionPerformed

    private void EditTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTestButtonActionPerformed
        // TODO add your handling code here:
        TSEditTest window = new TSEditTest();
        window.setVisible(true);
    }//GEN-LAST:event_EditTestButtonActionPerformed

    private void RemoveTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTestButtonActionPerformed
        // TODO add your handling code here:
        TSRemoveTest window = new TSRemoveTest();
        window.setVisible(true);
    }//GEN-LAST:event_RemoveTestButtonActionPerformed

    private void ViewTestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTestsButtonActionPerformed
        // TODO add your handling code here:
        TSViewTests window = new TSViewTests();
        window.setVisible(true);
    }//GEN-LAST:event_ViewTestsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TSMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TSMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TSMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TSMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TSMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClassButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton EditClassButton;
    private javax.swing.JButton EditTestButton;
    private javax.swing.JButton NewTestButton;
    private javax.swing.JButton RemoveClassButton;
    private javax.swing.JButton RemoveTestButton;
    private javax.swing.JButton ViewClassesButton;
    private javax.swing.JButton ViewTestsButton;
    // End of variables declaration//GEN-END:variables
}
